### ISSUE TITLE
Exception Handler 생성

### ISSUE THREAD

**Issue by gouyeonch** [donggukthon/donggukthon_2023_9_B#14]
## Task
- [x] Exception Handler 생성
- [ ] api 별 추가 테스트
- [ ] Excption Handler api별로 추가
