### ISSUE TITLE
스프링 부트 버전 업그레이드 (2.7.13 -> 3.0.9)로 인한 스프링 시큐리티 수정 & 로그인 기능 일부 수정

### ISSUE THREAD

**Issue by bbbang105** [donggukthon/donggukthon_2023_9_B#17]
## Describe the bug
- 더이상 사용하지 않는 일부 메소드 존재
- `has_snowman` , `is_plus` 변수가 초기화되지 않음
- 카카오톡 리다이렉트 메소드 POST를 3.x 이상부터는 더이상 사용하지 않음
## Task
- [x] 사용하지 않는 메소드 수정
- [x] 전역 변수 -> 로컬 변수로 수정
- [x] POST -> client_secret_post 로 수정
