### ISSUE TITLE
도커 & GCP로 배포 & 도메인 연결

### ISSUE THREAD

**Issue by bbbang105** [donggukthon/donggukthon_2023_9_B#19]
## Task
- [x] 프론트엔드,백엔드 도커파일 작성
- [x] 백엔드 deploy.sh 파일 작성
- [x] 프론트엔드, 백엔드 도커 이미지 생성 및 도커 허브 푸시
- [x] GCP 인스턴스 생성 및 연결
- [x] Nginx 설정
- [x] 도커 컴포즈 파일 FileZilla 사용하여 인스턴스에 업로드
- [x] 도커 허브에서 이미지 pull 받아 실행
- [x] 도메인 연결하여 https 적용
